# server.port=8083
# eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
# spring.data.mongodb.uri=mongodb://localhost:27017/AIRecomendation
# spring.data.mongodb.database=AIRecomendation

# spring.kafka.producer.bootstrap-servers=localhost:9092
# spring.kafka.consumer.group-id=activity-consumer-group
# spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
# spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# spring.kafka.consumer.properties.spring.json.trusted.packages=*
# spring.kafka.consumer.properties.spring.json.use.type.headers=false
# spring.kafka.consumer.properties.spring.json.value.default.type=com.fitness.AiService.model.Activity

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/AIRecomendation
      database: AIRecomendation

  kafka:
    producer:
      bootstrap-servers: localhost:9092

    consumer:
      bootstrap-servers: localhost:9092
      group-id: activity-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring:
          json:
            trusted:
              packages: "*"
            use:
              type:
                headers: false
            value:
              default:
                type: com.fitness.AiService.model.Activity
